kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "acid-main"
  namespace: "default"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "14"
  numberOfInstances: 3
  enableMasterLoadBalancer: true
  volume:
    size: "10Gi"
  users:
    mrbs: []
    canvas: []
  databases:
    mrbs: mrbs
    canvas: canvas
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
